export type NodeStatus = 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED' | 'BLOCKED';

export interface ChecklistItem {
  id: string;
  text: string;
  completed: boolean;
}

export interface RoadmapNode {
  id: string;
  title: string;
  description: string;
  status: NodeStatus;
  parentId: string | null; // If null, it is a main step. If set, it's a subnode of that parent.
  checklist: ChecklistItem[];
  createdAt: string;
  dueDate?: string; // Optional deadline date string (YYYY-MM-DD)
  durationDays?: number; // Optional duration in days
  timingType?: 'days' | 'date'; // Type of timing used
}

export interface RoadmapPath {
  id: string;
  title: string;
  description: string;
  color: string; // e.g., 'indigo', 'emerald', 'amber', 'rose', 'sky'
  nodes: RoadmapNode[]; // Contains both main nodes (parentId is null) and subnodes
  dueDate?: string; // Optional deadline date string (YYYY-MM-DD)
  durationDays?: number;
  timingType?: 'days' | 'date';
}

export interface Program {
  id: string;
  title: string;
  description: string;
  paths: RoadmapPath[];
  createdAt: string;
  dueDate?: string; // Optional deadline date string (YYYY-MM-DD)
  durationDays?: number;
  timingType?: 'days' | 'date';
}

export interface Challenge {
  id: string;
  title: string;
  durationDays: number;
  completedDays: number[]; // list of days (e.g., [1, 2, 3, 15] for a 30-day challenge)
  createdAt: string;
  isArchived?: boolean;
}

export type AppTheme = 'cyber-gradient' | 'forest-zen' | 'sunset-glow' | 'royal-classic' | 'midnight-deep' | 'light-emerald' | 'light-royal' | 'light-warm';
export type AppMode = 'simple' | 'advanced' | 'diagram';
export type AppTab = 'programs' | 'challenges' | 'daily-todos' | 'weekly-planner' | 'strategic-mind-map' | 'events' | 'ai-consultant';

export interface BrainstormingNode {
  id: string;
  text: string;
  x: number;
  y: number;
  color: string;
  children: string[];
  tasks: ChecklistItem[];
}

export interface BrainstormingProject {
  id: string;
  title: string;
  description?: string;
  nodes: BrainstormingNode[];
  createdAt: string;
  isArchived: boolean;
}

export interface WeeklyTask {
  id: string;
  text: string;
  time?: string;
  day: number;
  completed: boolean;
  order?: number;
}

export interface MindMapNode {
  id: string;
  text: string;
  x: number;
  y: number;
  color: string;
  children: string[]; // array of child node IDs
}

export interface TodoSubTask {
  id: string;
  title: string;
  completed: boolean;
}

export interface TodoItem {
  id: string;
  title: string;
  description?: string;
  completed: boolean;
  subTasks: TodoSubTask[];
  createdAt: string;
  isPinned?: boolean;
  isAutoGenerated?: boolean;
  sourceEventId?: string;
}

export interface CalendarEvent {
  id: string;
  title: string;
  description?: string;
  type: 'birthday' | 'anniversary' | 'conference' | 'other';
  date: string; // Jalali date format "YYYY/MM/DD"
  isYearly?: boolean;
  createdAt: string;
}

